In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a2.shape

(2, 3)

In [6]:
# Number of dimension
a2.ndim

2

In [7]:
a3 = np.array([[[0.5, 1.5, 2.5]], [[0.25, 0.5, 0.75]]])
a3

array([[[0.5 , 1.5 , 2.5 ]],

       [[0.25, 0.5 , 0.75]]])

In [8]:
a3.dtype

dtype('float64')

In [9]:
a3.size

6

In [14]:
# Generating Array filled with zeros

a4 = np.zeros((3, 4))
a4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# Generating Array from number to number plaicing only odd numbers
a5 = np.arange(0,10, 2)
a5

array([0, 2, 4, 6, 8])

In [16]:
# Generating Array filled with random numbers
a6 = np.random.randint(0, 100, size=(3, 4))
a6

array([[87, 64, 16, 83],
       [48, 67,  9, 43],
       [ 3, 90,  5, 67]], dtype=int32)