In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a3 = np.array([[[0.5, 1.5, 2.5]], [[0.25, 0.5, 0.75]]])
a3

array([[[0.5 , 1.5 , 2.5 ]],

       [[0.25, 0.5 , 0.75]]])

In [5]:
# Selecting a data
a3[0][0][0]

np.float64(0.5)

In [6]:
# Selecting a column
a3[:,:,2:]

array([[[2.5 ]],

       [[0.75]]])

In [7]:
# Adding arrays
a4 = a1 + [3, 2, 1]
a4

array([4, 4, 4])

In [8]:
# Subtraction
a4 = a4 - a1
a4

array([3, 2, 1])

In [9]:
# Multiplication

a5 = a2 * a4
a5

array([[ 3,  4,  3],
       [12, 10,  6]])

In [10]:
# Floor
print(a5 // 2)

[[1 2 1]
 [6 5 3]]


In [11]:
# Modulo
print(a5 % 2)

[[1 0 1]
 [0 0 0]]


In [14]:
# Mean - The average value of a set of numbers.
print(np.mean(a5))

6.333333333333333


In [15]:
# Variance - How spread out the numbers are from the mean.
print(np.var(a5))

12.222222222222221


In [16]:
# Standard Deviation - The typical distance each number is from the mean.
print(np.std(a5))

3.496029493900505
