In [1]:
import numpy as np

In [2]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a3 = np.array([[[0.5, 1.5, 2.5]], [[0.25, 0.5, 0.75]]])
a3

array([[[0.5 , 1.5 , 2.5 ]],

       [[0.25, 0.5 , 0.75]]])

In [4]:
a4 = a2.reshape(2, 3, 1)
a4

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [5]:
a5 = a4 * a3
a5

array([[[0.5 , 1.5 , 2.5 ],
        [1.  , 3.  , 5.  ],
        [1.5 , 4.5 , 7.5 ]],

       [[1.  , 2.  , 3.  ],
        [1.25, 2.5 , 3.75],
        [1.5 , 3.  , 4.5 ]]])

In [6]:
# Transpose
a5.T

array([[[0.5 , 1.  ],
        [1.  , 1.25],
        [1.5 , 1.5 ]],

       [[1.5 , 2.  ],
        [3.  , 2.5 ],
        [4.5 , 3.  ]],

       [[2.5 , 3.  ],
        [5.  , 3.75],
        [7.5 , 4.5 ]]])

In [7]:
# Matrix Multiplication
np.dot(a4, a5)


ValueError: shapes (2,3,1) and (2,3,3) not aligned: 1 (dim 2) != 3 (dim 1)