In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)

sindex = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun",]
scolumns = ["Almond Butter", "Peanat Butter", "Cashhew Butter"]

sales_amounts = np.random.randint(20, size=(7, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7],
       [14, 17,  5],
       [13,  8,  9]], dtype=int32)

In [5]:
weekly_sales = pd.DataFrame(sales_amounts, index=sindex, columns=scolumns)
weekly_sales

Almond Butter  Peanat Butter  Cashhew Butter
Mon             12             15               0
Tue              3              3               7
Wed              9             19              18
Thu              4              6              12
Fri              1              6               7
Sat             14             17               5
Sun             13              8               9

In [6]:
prices = np.array([15, 10, 20])
prices

array([15, 10, 20])

In [9]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], columns=scolumns)
butter_prices

Almond Butter  Peanat Butter  Cashhew Butter
Price             15             10              20

In [10]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([330, 215, 685, 360, 215, 480, 455])

In [13]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue  Wed  Thu  Fri  Sat  Sun
Price  330  215  685  360  215  480  455

In [ ]:
weekly_sales["Total"] 