In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [4]:
a2 > a1

array([[False, False, False],
       [ True,  True,  True]])

In [5]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])