In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(10, size=(5, 5))
a1

array([[7, 6, 9, 1, 0],
       [2, 9, 1, 7, 7],
       [3, 9, 2, 1, 2],
       [3, 1, 9, 5, 9],
       [5, 5, 3, 9, 5]], dtype=int32)

In [3]:
np.sort(a1)

array([[0, 1, 6, 7, 9],
       [1, 2, 7, 7, 9],
       [1, 2, 2, 3, 9],
       [1, 3, 5, 9, 9],
       [3, 5, 5, 5, 9]], dtype=int32)

In [7]:
# Show indexes
np.argsort(a1)

array([[4, 3, 1, 0, 2],
       [2, 0, 3, 4, 1],
       [3, 2, 4, 0, 1],
       [1, 0, 3, 2, 4],
       [2, 0, 1, 4, 3]])